---
title: "Só 21 cidades"
author: "Gregorio U"
date: "12/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
base <- read_excel("D:/ATUALIZA_PASTA_d/A Nova pasta/Milton27/Milton27.xlsx")
base$Bolsonaro <- 100*base$Bolsonaro2018_turno2
base$`% Superior Completo` <- base$superior_comp
base <- subset(base, select=c(Cidade,`% Superior Completo`,Bolsonaro))
linhas<-c(2,4,6,11,16,26)
base <- base[-c(linhas),] # rm 6 cidades
```


```{r}
fit <- lm(Bolsonaro~`% Superior Completo`, data=base)
base$predicted <- predict(fit)   # Save the predicted values
base$residuals <- residuals(fit) # Save the residual values

ggplot(base, aes(x = `% Superior Completo`, y =Bolsonaro)) +
  geom_smooth(method = "lm", se = FALSE, color = "lightgrey") + geom_text(label=base$Cidade)+       
  geom_segment(aes(xend = `% Superior Completo`, yend = predicted), alpha = .2) +      # draw line from point to line
  geom_point(aes(color = abs(residuals), size = abs(residuals))) +  # size of the points
  scale_color_continuous(low = "green", high = "red") +             # colour of the points mapped to residual size - green smaller, red larger
  guides(color = FALSE, size = FALSE) +                             # Size legend removed
  geom_point(aes(y = predicted), shape = 1) +
  theme_bw()



```

# só pra constar
```{r}
summary(fit)
```

